services:
  nginx:
    image: nginx:1.28
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - "${NGINX_EXPOSED_PORT}:80"
    volumes:
      - ./moodle:/var/www/moodle
      - ./moodledata:/var/www/moodledata
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: yvikt/php:8.4-fpm-moodle
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - default      # default network prefixed by COMPOSE_PROJECT_NAME=moodle51php84
      - mail-bridge  # external network - interact with mail server running in separate env
    volumes:
      - ./moodle:/var/www/moodle
      - ./moodledata:/var/www/moodledata
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/99-custom.ini:ro
#      - ./docker/php/fpm-extra.conf:/usr/local/etc/php-fpm.d/zz-fpm-extra.conf:ro
      - ./data/docker/php/root:/root
    environment:
      DB_HOST: ${DB_HOST}
      DB_TYPE: ${DB_TYPE}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      WWW_ROOT: ${WWW_ROOT}
      DATA_ROOT: ${DATA_ROOT}
      COMPOSER_NO_DEV: 1
      COMPOSER_OPTIMIZE_AUTOLOADER: 1

  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MARIADB_USER: ${DB_USER}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/db/root:/root
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf:ro

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data

#  docker network create mail-bridge
networks:
  mail-bridge:
    external: true